---
dist: trusty
language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
  - node_modules
install: true
stages:
  - Install
  - Test
  - Benchmark
jobs:
  include:
    - stage: Install
      script: yarn

    - stage: Test
      script: yarn ci:lint

    - stage: Benchmark
      script: yarn benchmark:array-indexof-set-has
    -
      script: yarn benchmark:map-for-each
    -
      script: yarn benchmark:regex-constructor
    -
      script: yarn benchmark:regex-match-alphanum
